### ISSUE TITLE
Gismo_Address To Location (utf-8 )

### ISSUE THREAD

**Issue by AntonelloDN** [stgeorges/gismo#4]
Hi @Alliages,

I suggest that you add 'utf-8 encode' to your location component.
I like to think people can write also special characters of their own language.

> timeZone = 0; elevation = 0  # default. These two inputs are not important for OSM and terrain components
> url = "http://nominatim.openstreetmap.org/search"
> address = urllib.quote_plus(address.encode('utf-8'))
> format="jsonv2
> [...]

<em>Antonello</em>

**Comment by stgeorges** [comment]
Hi @AntonelloDN ,

This would be a great addition!! Thank you!!
@Alliages can we implement this to your "Address to Location" component?

**Comment by Alliages** [comment]
yes off course...
If you have'nt done it since then, i'll do it next week

**Comment by stgeorges** [comment]
Hi @Alliages ,
It's better if author of the component does the implementations. Unless there is some urgent bug.
We are eager to see the implementation next week! Thank you!
@AntonelloDN , hey thank you too!!
