### ISSUE TITLE
solution exception light exception object has no attributes

### ISSUE THREAD

**Issue by psnigdhasai** [stgeorges/gismo#9]
<img width="492" alt="Screen Shot 2019-07-14 at 3 19 28 PM" src="https://user-images.githubusercontent.com/52518368/61181965-d00fd500-a64a-11e9-9b99-df4594fd40fa.png">

**Comment by psnigdhasai** [comment]
solution exception light exception object has no attributes

**Comment by stgeorges** [comment]
Hi @psnigdhasai,
[Gismo requires](https://github.com/stgeorges/gismo#requirements) Ghpython component of 0.6.0.3 version at least.
Download it from here:
https://www.food4rhino.com/app/ghpython
